name: Run MSO Scraper Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Run scraper
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          pwd
          ls -R
          python clean_scraper.py
